steps:
  # Build the "hello, world" Go binary.
  # - name: "gcr.io/cloud-builders/go"
  #   args: ["install", "hello"]
  #   env: ["PROJECT_ROOT=hello"]
  # Upload it into a GCS bucket.
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "rsync", "-d", "-r", "testdir/", "gs://frssbi-sandbox/"]
